FROM node:22-alpine AS base

# ---------------------------------
# Stage 1: Builder
# ---------------------------------
FROM base AS builder

ARG API_BASE_URL=""
ARG REPOSITORY_URL=""

ENV NEXT_PUBLIC_API_URL=${API_BASE_URL}
ENV NEXT_PUBLIC_APP_REPO=${API_BASE_URL}

WORKDIR /app

# Enable pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy root package.json and lockfile
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Copy all project files
COPY . .

ENV NODE_ENV=production

# Build Next.js app
RUN pnpm build

# ---------------------------------
# Stage 2: Runner
# ---------------------------------
FROM base AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000

# Create a non-root user to run the app
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy public assets
COPY --from=builder /app/public ./public

# Copy standalone build output (optimized by Next.js)
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

# server.js is created by Next.js during the standalone build output
# https://nextjs.org/docs/pages/api-reference/config/next-config-js/output
CMD ["node", "server.js"]