"""'application step user id'

Revision ID: 07d97858223f
Revises: 8ed990326196
Create Date: 2025-11-06 16:42:36.528793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d97858223f'
down_revision: Union[str, Sequence[str], None] = '8ed990326196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'application_steps', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
        'fk_application_steps_user_id', 'application_steps', 'users',
        ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_application_steps_user_id', 'application_steps', type_='foreignkey')
    op.drop_column('application_steps', 'user_id')
    # ### end Alembic commands ###
