"""add user_feedbacks table

Revision ID: 49792420ad7b
Revises: b2c3d4e5f6a1
Create Date: 2026-03-26 10:18:10.279560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49792420ad7b'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedbacks',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_user_feedbacks_score'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_feedbacks_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_user_feedbacks')
    )
    op.create_index('idx_user_feedbacks_user_id', 'user_feedbacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_feedbacks_user_id', table_name='user_feedbacks')
    op.drop_table('user_feedbacks')
    # ### end Alembic commands ###
