"""'strict column for steps definition'

Revision ID: 83243abba58d
Revises: a33d23ad4276
Create Date: 2025-09-20 02:42:02.385263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83243abba58d'
down_revision: Union[str, Sequence[str], None] = 'a33d23ad4276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'steps_definition', sa.Column('strict', sa.Boolean()))
    op.execute("UPDATE steps_definition SET strict = false")
    op.execute("UPDATE steps_definition SET strict = true " +
               "WHERE name IN ('Denied', 'Offer')")
    op.alter_column(
        'steps_definition', 'strict',
        existing_type=sa.BOOLEAN(),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps_definition', 'strict')
    # ### end Alembic commands ###
