"""'step table renamed'

Revision ID: 8ed990326196
Revises: 83243abba58d
Create Date: 2025-09-22 22:52:35.798806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ed990326196'
down_revision: Union[str, Sequence[str], None] = '83243abba58d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('steps', 'application_steps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('application_steps', 'steps')
    # ### end Alembic commands ###
