"""'column names and types adjustments'

Revision ID: a33d23ad4276
Revises: e3abe9dc93d4
Create Date: 2025-09-19 19:13:15.399107

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33d23ad4276'
down_revision: Union[str, Sequence[str], None] = 'e3abe9dc93d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'applications', sa.Column('last_step_id', sa.Integer(), nullable=True)
    )
    op.alter_column(
        'applications',
        'mode',
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
    )
    op.drop_constraint(
        op.f('fk_applications_last_step'), 'applications', type_='foreignkey'
    )
    op.create_foreign_key(
        op.f('fk_applications_last_step_id'),
        'applications',
        'steps_definition',
        ['last_step_id'],
        ['id'],
    )
    op.drop_column('applications', 'last_step')
    op.alter_column(
        'users',
        'username',
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'username',
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.add_column(
        'applications',
        sa.Column(
            'last_step', sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        op.f('fk_applications_last_step_id'),
        'applications',
        type_='foreignkey',
    )
    op.create_foreign_key(
        op.f('fk_applications_last_step'),
        'applications',
        'steps_definition',
        ['last_step'],
        ['id'],
    )
    op.alter_column(
        'applications',
        'mode',
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
    )
    op.drop_column('applications', 'last_step_id')
    # ### end Alembic commands ###
