"""''link_to_job' column added to 'applications' table'

Revision ID: d997fc17b3d3
Revises: 07d97858223f
Create Date: 2025-12-18 17:11:23.404757

"""

from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd997fc17b3d3'
down_revision: Union[str, Sequence[str], None] = '07d97858223f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    now = datetime.now(timezone.utc)
    platforms_table = sa.table(
        'platforms',
        sa.column('name', sa.String),
        sa.column('url', sa.String),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        platforms_table,
        [{'name': 'Referral', 'url': '', 'created_at': now}]
    )

    op.add_column('applications', sa.Column(
        'link_to_job', sa.String(length=2083), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'link_to_job')

    platforms_table = sa.table(
        'platforms',
        sa.column('name', sa.String),
        sa.column('url', sa.String),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )
    op.execute(sa.text("""
        UPDATE applications
        SET platform_id = (
            SELECT id FROM platforms WHERE lower(name) = 'linkedin' LIMIT 1
        )
        WHERE platform_id = (
            SELECT id FROM platforms WHERE lower(name) = 'referral' LIMIT 1
        )
    """))
    op.execute(
        platforms_table.delete().where(platforms_table.c.name == 'Referral')
    )
    
    # ### end Alembic commands ###
