"""''link_to_job' column added to 'applications' table'

Revision ID: d997fc17b3d3
Revises: 07d97858223f
Create Date: 2025-12-18 17:11:23.404757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd997fc17b3d3'
down_revision: Union[str, Sequence[str], None] = '07d97858223f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column(
        'link_to_job', sa.String(length=2083), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'link_to_job')
    # ### end Alembic commands ###
